service: flat-service

# Remember to reference the plugin
plugins:
  - serverless-webpack
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    PG_HOST: dvyshka-db.cwjlobdvfzsg.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: dvyshka
    PG_USERNAME: postgres
    PG_PASSWORD: Gr3YRckw0eRjhphud3DN
  region: eu-west-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    # You must have the documentation object
  documentation:
    # this is general info about the API
    # api:
    #   info:
    #     version: '2'
    #     title: Example API
    #     description: Some example API
    #     termsOfService: https://www.google.com
    #     contact:
    #       name: The contact person
    #       url: https://www.serverless.com/framework
    #       email: some-fake@email.com
    #     license:
    #       name: The license
    #       url: https://www.github.com
    #   tags:
    #     -
    #       name: Tag1
    #       description: The first tag
    #     -
    #       name: Tag2
    #       description: That other tag that we all love
    # Now we describe all the models that we use
    models:
      -
        name: GetFlatList
        contentType: application/json
        schema:
          type: array
          items:
            type: object
            properties:
              id:
                type: string


functions:

  getFlatList:
    handler: ./handlers/getFlatList.getFlatList
    events:
      - http:
          path: flats
          method: get
          documentation:
            summary: Get flats
            description: Get flats
            tags:
              - Getting flats
            methodResponses:
              -
                statusCode: 200
                responseModels:
                  application/json: GetFlatList


  getFlatById:
    handler: ./handlers/getFlatById.getFlatById
    events:
      - http:
          path: flats/{flatId}
          method: get


  postFlat:
    handler: ./handlers/postFlat.postFlat
    events:
      - http:
          path: flats/post
          method: post
